/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    courses: Course;
    modules: Module;
    lessons: Lesson;
    'community-events': CommunityEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    'community-events': CommunityEventsSelect<false> | CommunityEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  totpSecret?: string | null;
  hasTotp?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  slug?: string | null;
  description?: string | null;
  coverImage?: (number | null) | Media;
  order: number;
  publishedAt?: string | null;
  /**
   * When checked, this course is excluded from the public API and all calculations.
   */
  isHidden?: boolean | null;
  /**
   * This course is locked until the selected prerequisite course is fully completed. Lectures are always accessible.
   */
  prerequisiteCourse?: (number | null) | Course;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  title: string;
  slug?: string | null;
  course: number | Course;
  order: number;
  /**
   * When checked, this module is excluded from the public API and all calculations.
   */
  isHidden?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  slug?: string | null;
  module: number | Module;
  order: number;
  type: 'lecture' | 'test' | 'coding_task' | 'review_task';
  /**
   * Shown to students. For review tasks, use this as the learner-facing task description.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  questions?:
    | {
        question: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        options?:
          | {
              label: string;
              isCorrect?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Language used in the Monaco editor and passed to the AI reviewer.
   */
  codingLanguage?: ('solidity' | 'rust' | 'typescript') | null;
  /**
   * Initial code shown in the student's Monaco editor. Leave empty for a blank editor.
   */
  starterCode?: string | null;
  /**
   * What the student's code should achieve — fed to the AI reviewer. NOT shown to students. Example: "The contract must protect against reentrancy using checks-effects-interactions or ReentrancyGuard."
   */
  aiExpectedResult?: string | null;
  /**
   * Visible test case descriptions shown to the student (like LeetCode examples). Also included in the AI review prompt as additional context.
   */
  codingTestCases?:
    | {
        title: string;
        /**
         * Describe what this test case checks.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Required when executable test cases are defined. TS form: `solve(nums: number[], target: number): number[]`. Solidity form: `function add(uint256 a, uint256 b) external view returns (uint256)`.
   */
  functionSignature?: string | null;
  /**
   * Optional. Name of the contract to deploy. Defaults to the first contract in the source.
   */
  solidityContractName?: string | null;
  /**
   * Optional JSON array of constructor arguments, e.g. `["0x1234...", "1000"]`.
   */
  solidityConstructorArgs?: string | null;
  /**
   * Each row runs in the browser against the student's code. `inputJson` is a JSON array of arguments; `expectedJson` is the expected return value as JSON. For Solidity uint256/int256/bytes/address, use string-encoded values. Leave this entire array empty to keep AI-only grading (legacy mode).
   */
  executableTestCases?:
    | {
        /**
         * JSON array of args. Example: `[[2,7,11,15], 9]`.
         */
        inputJson: string;
        /**
         * Expected return value as JSON. Example: `[0, 1]` or `"42"`. When `postCheckJson` is set, this is compared to the post-check view return instead of the main call return.
         */
        expectedJson: string;
        /**
         * Optional. Solidity only. ETH (in wei) sent with the main call as msg.value. Decimal string. Example: `"5"` or `"1000000000000000000"`.
         */
        valueWei?: string | null;
        /**
         * Optional. Solidity only. JSON `{"signature": "function tokensSold() external view returns (uint256)", "args": []}`. When set, the runner calls this view AFTER the main call and compares its return to `expectedJson`.
         */
        postCheckJson?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Short context for the AI reviewer (not shown to students via the public API).
   */
  aiTaskSummary?: string | null;
  /**
   * Acceptable approaches / solution hints for the model (not shown to students via the public API).
   */
  aiPossibleSolutions?: string | null;
  /**
   * Each row is one graded item the AI will evaluate as pass/fail.
   */
  reviewGradingTasks?:
    | {
        title: string;
        /**
         * What the AI should verify for this row (pass/fail per rubric).
         */
        criteria?: string | null;
        /**
         * When enabled, criteria text is not shown to learners in the app or API (still used for AI review). Use for spoilers or solution hints.
         */
        hideCriteriaFromLearner?: boolean | null;
        /**
         * Learner must earn full points on this row for the lesson to count as passed (when any row is required, overall pass depends only on required rows).
         */
        isRequired?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * GitHub URL of the course repo students should fork (Fork button). When set, submissions must be a GitHub fork whose upstream matches this repository; the original repo URL alone is rejected.
   */
  templateRepoUrl?: string | null;
  /**
   * Repo-relative paths. Each row is one exact file or one glob; every matching file is fetched for AI review (duplicate paths across rows are deduped). Literals: e.g. src/Contract.sol, README.md. Single-segment * (does not cross /): e.g. contracts/*.sol, tests/*.spec.ts. Recursive **: e.g. contracts/** /*.sol, ** /*.sol, ** /Contract.sol. ? and [a-z] character classes are supported. If a glob matches no files in the student repo, submission fails like a missing file.
   */
  reviewPaths?:
    | {
        path: string;
        id?: string | null;
      }[]
    | null;
  /**
   * When checked, this lesson is excluded from the public API and all calculations.
   */
  isHidden?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-events".
 */
export interface CommunityEvent {
  id: number;
  title: string;
  slug?: string | null;
  description: string;
  eventDate?: string | null;
  photo: number | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'community-events';
        value: number | CommunityEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  totpSecret?: T;
  hasTotp?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  order?: T;
  publishedAt?: T;
  isHidden?: T;
  prerequisiteCourse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  course?: T;
  order?: T;
  isHidden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  module?: T;
  order?: T;
  type?: T;
  content?: T;
  questions?:
    | T
    | {
        question?: T;
        options?:
          | T
          | {
              label?: T;
              isCorrect?: T;
              id?: T;
            };
        id?: T;
      };
  codingLanguage?: T;
  starterCode?: T;
  aiExpectedResult?: T;
  codingTestCases?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  functionSignature?: T;
  solidityContractName?: T;
  solidityConstructorArgs?: T;
  executableTestCases?:
    | T
    | {
        inputJson?: T;
        expectedJson?: T;
        valueWei?: T;
        postCheckJson?: T;
        id?: T;
      };
  aiTaskSummary?: T;
  aiPossibleSolutions?: T;
  reviewGradingTasks?:
    | T
    | {
        title?: T;
        criteria?: T;
        hideCriteriaFromLearner?: T;
        isRequired?: T;
        id?: T;
      };
  templateRepoUrl?: T;
  reviewPaths?:
    | T
    | {
        path?: T;
        id?: T;
      };
  isHidden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-events_select".
 */
export interface CommunityEventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  eventDate?: T;
  photo?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}