/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import {
  pgSchema,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  type AnyPgColumn,
  jsonb,
} from 'drizzle-orm/pg-core'
import { sql, relations } from 'drizzle-orm'
export const db_schema = pgSchema('payload')
export const enum_lessons_type = db_schema.enum('enum_lessons_type', ['lecture', 'test', 'coding_task', 'review_task'])
export const enum_lessons_coding_language = db_schema.enum('enum_lessons_coding_language', [
  'solidity',
  'rust',
  'typescript',
])

export const users_sessions = db_schema.table(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = db_schema.table(
  'users',
  {
    id: serial('id').primaryKey(),
    totpSecret: varchar('totp_secret'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = db_schema.table(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const courses_tags = db_schema.table(
  'courses_tags',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    value: varchar('value').notNull(),
  },
  (columns) => [
    index('courses_tags_order_idx').on(columns._order),
    index('courses_tags_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [courses.id],
      name: 'courses_tags_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const courses = db_schema.table(
  'courses',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug'),
    description: varchar('description'),
    coverImage: integer('cover_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    durationHours: numeric('duration_hours', { mode: 'number' }),
    order: numeric('order', { mode: 'number' }).notNull().default(0),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    isHidden: boolean('is_hidden').default(false),
    prerequisiteCourse: integer('prerequisite_course_id').references((): AnyPgColumn => courses.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    uniqueIndex('courses_slug_idx').on(columns.slug),
    index('courses_cover_image_idx').on(columns.coverImage),
    index('courses_prerequisite_course_idx').on(columns.prerequisiteCourse),
    index('courses_updated_at_idx').on(columns.updatedAt),
    index('courses_created_at_idx').on(columns.createdAt),
  ],
)

export const modules = db_schema.table(
  'modules',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug'),
    course: integer('course_id')
      .notNull()
      .references(() => courses.id, {
        onDelete: 'set null',
      }),
    order: numeric('order', { mode: 'number' }).notNull(),
    isHidden: boolean('is_hidden').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('modules_course_idx').on(columns.course),
    index('modules_updated_at_idx').on(columns.updatedAt),
    index('modules_created_at_idx').on(columns.createdAt),
  ],
)

export const lessons_faq = db_schema.table(
  'lessons_faq',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    question: varchar('question').notNull(),
    answer: varchar('answer').notNull(),
  },
  (columns) => [
    index('lessons_faq_order_idx').on(columns._order),
    index('lessons_faq_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons.id],
      name: 'lessons_faq_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_questions_options = db_schema.table(
  'lessons_questions_options',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: jsonb('label'),
    isCorrect: boolean('is_correct').default(false),
  },
  (columns) => [
    index('lessons_questions_options_order_idx').on(columns._order),
    index('lessons_questions_options_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons_questions.id],
      name: 'lessons_questions_options_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_questions = db_schema.table(
  'lessons_questions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    question: jsonb('question'),
  },
  (columns) => [
    index('lessons_questions_order_idx').on(columns._order),
    index('lessons_questions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons.id],
      name: 'lessons_questions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_solidity_constructor_args = db_schema.table(
  'lessons_solidity_constructor_args',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    value: varchar('value'),
  },
  (columns) => [
    index('lessons_solidity_constructor_args_order_idx').on(columns._order),
    index('lessons_solidity_constructor_args_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons.id],
      name: 'lessons_solidity_constructor_args_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_executable_test_cases = db_schema.table(
  'lessons_executable_test_cases',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name'),
    inputJson: varchar('input_json'),
    expectedJson: varchar('expected_json'),
  },
  (columns) => [
    index('lessons_executable_test_cases_order_idx').on(columns._order),
    index('lessons_executable_test_cases_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons.id],
      name: 'lessons_executable_test_cases_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_solidity_fixtures_constructor_args = db_schema.table(
  'lessons_solidity_fixtures_constructor_args',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    value: varchar('value'),
  },
  (columns) => [
    index('lessons_solidity_fixtures_constructor_args_order_idx').on(columns._order),
    index('lessons_solidity_fixtures_constructor_args_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons_solidity_fixtures.id],
      name: 'lessons_solidity_fixtures_constructor_args_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_solidity_fixtures = db_schema.table(
  'lessons_solidity_fixtures',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    alias: varchar('alias'),
    source: varchar('source'),
    contractName: varchar('contract_name'),
  },
  (columns) => [
    index('lessons_solidity_fixtures_order_idx').on(columns._order),
    index('lessons_solidity_fixtures_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons.id],
      name: 'lessons_solidity_fixtures_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_solidity_test_cases_steps_args = db_schema.table(
  'lessons_solidity_test_cases_steps_args',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    value: varchar('value'),
  },
  (columns) => [
    index('lessons_solidity_test_cases_steps_args_order_idx').on(columns._order),
    index('lessons_solidity_test_cases_steps_args_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons_solidity_test_cases_steps.id],
      name: 'lessons_solidity_test_cases_steps_args_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_solidity_test_cases_steps = db_schema.table(
  'lessons_solidity_test_cases_steps',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name'),
    functionName: varchar('function_name'),
    target: varchar('target'),
    valueWei: varchar('value_wei'),
    caller: varchar('caller'),
    hideFromLearner: boolean('hide_from_learner').default(false),
    expected: varchar('expected'),
    expectedRevert: varchar('expected_revert'),
  },
  (columns) => [
    index('lessons_solidity_test_cases_steps_order_idx').on(columns._order),
    index('lessons_solidity_test_cases_steps_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons_solidity_test_cases.id],
      name: 'lessons_solidity_test_cases_steps_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_solidity_test_cases = db_schema.table(
  'lessons_solidity_test_cases',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name'),
  },
  (columns) => [
    index('lessons_solidity_test_cases_order_idx').on(columns._order),
    index('lessons_solidity_test_cases_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons.id],
      name: 'lessons_solidity_test_cases_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_review_grading_tasks = db_schema.table(
  'lessons_review_grading_tasks',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    criteria: varchar('criteria'),
    hideCriteriaFromLearner: boolean('hide_criteria_from_learner').default(false),
    isRequired: boolean('is_required').default(false),
  },
  (columns) => [
    index('lessons_review_grading_tasks_order_idx').on(columns._order),
    index('lessons_review_grading_tasks_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons.id],
      name: 'lessons_review_grading_tasks_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons_review_paths = db_schema.table(
  'lessons_review_paths',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    path: varchar('path'),
  },
  (columns) => [
    index('lessons_review_paths_order_idx').on(columns._order),
    index('lessons_review_paths_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lessons.id],
      name: 'lessons_review_paths_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lessons = db_schema.table(
  'lessons',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug'),
    module: integer('module_id')
      .notNull()
      .references(() => modules.id, {
        onDelete: 'set null',
      }),
    order: numeric('order', { mode: 'number' }).notNull(),
    type: enum_lessons_type('type').notNull().default('lecture'),
    content: jsonb('content'),
    codingLanguage: enum_lessons_coding_language('coding_language'),
    starterCode: varchar('starter_code'),
    aiExpectedResult: varchar('ai_expected_result'),
    functionSignature: varchar('function_signature'),
    solidityContractName: varchar('solidity_contract_name'),
    aiTaskSummary: varchar('ai_task_summary'),
    templateRepoUrl: varchar('template_repo_url'),
    taskName: varchar('task_name'),
    isHidden: boolean('is_hidden').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('lessons_module_idx').on(columns.module),
    index('lessons_updated_at_idx').on(columns.updatedAt),
    index('lessons_created_at_idx').on(columns.createdAt),
  ],
)

export const community_events = db_schema.table(
  'community_events',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug'),
    description: varchar('description').notNull(),
    eventDate: timestamp('event_date', { mode: 'string', withTimezone: true, precision: 3 }),
    photo: integer('photo_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    content: jsonb('content'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    uniqueIndex('community_events_slug_idx').on(columns.slug),
    index('community_events_photo_idx').on(columns.photo),
    index('community_events_updated_at_idx').on(columns.updatedAt),
    index('community_events_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = db_schema.table(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = db_schema.table(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = db_schema.table(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    coursesID: integer('courses_id'),
    modulesID: integer('modules_id'),
    lessonsID: integer('lessons_id'),
    'community-eventsID': integer('community_events_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_courses_id_idx').on(columns.coursesID),
    index('payload_locked_documents_rels_modules_id_idx').on(columns.modulesID),
    index('payload_locked_documents_rels_lessons_id_idx').on(columns.lessonsID),
    index('payload_locked_documents_rels_community_events_id_idx').on(columns['community-eventsID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['coursesID']],
      foreignColumns: [courses.id],
      name: 'payload_locked_documents_rels_courses_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['modulesID']],
      foreignColumns: [modules.id],
      name: 'payload_locked_documents_rels_modules_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['lessonsID']],
      foreignColumns: [lessons.id],
      name: 'payload_locked_documents_rels_lessons_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['community-eventsID']],
      foreignColumns: [community_events.id],
      name: 'payload_locked_documents_rels_community_events_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = db_schema.table(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = db_schema.table(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = db_schema.table(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }).defaultNow().notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_courses_tags = relations(courses_tags, ({ one }) => ({
  _parentID: one(courses, {
    fields: [courses_tags._parentID],
    references: [courses.id],
    relationName: 'tags',
  }),
}))
export const relations_courses = relations(courses, ({ one, many }) => ({
  coverImage: one(media, {
    fields: [courses.coverImage],
    references: [media.id],
    relationName: 'coverImage',
  }),
  tags: many(courses_tags, {
    relationName: 'tags',
  }),
  prerequisiteCourse: one(courses, {
    fields: [courses.prerequisiteCourse],
    references: [courses.id],
    relationName: 'prerequisiteCourse',
  }),
}))
export const relations_modules = relations(modules, ({ one }) => ({
  course: one(courses, {
    fields: [modules.course],
    references: [courses.id],
    relationName: 'course',
  }),
}))
export const relations_lessons_faq = relations(lessons_faq, ({ one }) => ({
  _parentID: one(lessons, {
    fields: [lessons_faq._parentID],
    references: [lessons.id],
    relationName: 'faq',
  }),
}))
export const relations_lessons_questions_options = relations(lessons_questions_options, ({ one }) => ({
  _parentID: one(lessons_questions, {
    fields: [lessons_questions_options._parentID],
    references: [lessons_questions.id],
    relationName: 'options',
  }),
}))
export const relations_lessons_questions = relations(lessons_questions, ({ one, many }) => ({
  _parentID: one(lessons, {
    fields: [lessons_questions._parentID],
    references: [lessons.id],
    relationName: 'questions',
  }),
  options: many(lessons_questions_options, {
    relationName: 'options',
  }),
}))
export const relations_lessons_solidity_constructor_args = relations(lessons_solidity_constructor_args, ({ one }) => ({
  _parentID: one(lessons, {
    fields: [lessons_solidity_constructor_args._parentID],
    references: [lessons.id],
    relationName: 'solidityConstructorArgs',
  }),
}))
export const relations_lessons_executable_test_cases = relations(lessons_executable_test_cases, ({ one }) => ({
  _parentID: one(lessons, {
    fields: [lessons_executable_test_cases._parentID],
    references: [lessons.id],
    relationName: 'executableTestCases',
  }),
}))
export const relations_lessons_solidity_fixtures_constructor_args = relations(
  lessons_solidity_fixtures_constructor_args,
  ({ one }) => ({
    _parentID: one(lessons_solidity_fixtures, {
      fields: [lessons_solidity_fixtures_constructor_args._parentID],
      references: [lessons_solidity_fixtures.id],
      relationName: 'constructorArgs',
    }),
  }),
)
export const relations_lessons_solidity_fixtures = relations(lessons_solidity_fixtures, ({ one, many }) => ({
  _parentID: one(lessons, {
    fields: [lessons_solidity_fixtures._parentID],
    references: [lessons.id],
    relationName: 'solidityFixtures',
  }),
  constructorArgs: many(lessons_solidity_fixtures_constructor_args, {
    relationName: 'constructorArgs',
  }),
}))
export const relations_lessons_solidity_test_cases_steps_args = relations(
  lessons_solidity_test_cases_steps_args,
  ({ one }) => ({
    _parentID: one(lessons_solidity_test_cases_steps, {
      fields: [lessons_solidity_test_cases_steps_args._parentID],
      references: [lessons_solidity_test_cases_steps.id],
      relationName: 'args',
    }),
  }),
)
export const relations_lessons_solidity_test_cases_steps = relations(
  lessons_solidity_test_cases_steps,
  ({ one, many }) => ({
    _parentID: one(lessons_solidity_test_cases, {
      fields: [lessons_solidity_test_cases_steps._parentID],
      references: [lessons_solidity_test_cases.id],
      relationName: 'steps',
    }),
    args: many(lessons_solidity_test_cases_steps_args, {
      relationName: 'args',
    }),
  }),
)
export const relations_lessons_solidity_test_cases = relations(lessons_solidity_test_cases, ({ one, many }) => ({
  _parentID: one(lessons, {
    fields: [lessons_solidity_test_cases._parentID],
    references: [lessons.id],
    relationName: 'solidityTestCases',
  }),
  steps: many(lessons_solidity_test_cases_steps, {
    relationName: 'steps',
  }),
}))
export const relations_lessons_review_grading_tasks = relations(lessons_review_grading_tasks, ({ one }) => ({
  _parentID: one(lessons, {
    fields: [lessons_review_grading_tasks._parentID],
    references: [lessons.id],
    relationName: 'reviewGradingTasks',
  }),
}))
export const relations_lessons_review_paths = relations(lessons_review_paths, ({ one }) => ({
  _parentID: one(lessons, {
    fields: [lessons_review_paths._parentID],
    references: [lessons.id],
    relationName: 'reviewPaths',
  }),
}))
export const relations_lessons = relations(lessons, ({ one, many }) => ({
  module: one(modules, {
    fields: [lessons.module],
    references: [modules.id],
    relationName: 'module',
  }),
  faq: many(lessons_faq, {
    relationName: 'faq',
  }),
  questions: many(lessons_questions, {
    relationName: 'questions',
  }),
  solidityConstructorArgs: many(lessons_solidity_constructor_args, {
    relationName: 'solidityConstructorArgs',
  }),
  executableTestCases: many(lessons_executable_test_cases, {
    relationName: 'executableTestCases',
  }),
  solidityFixtures: many(lessons_solidity_fixtures, {
    relationName: 'solidityFixtures',
  }),
  solidityTestCases: many(lessons_solidity_test_cases, {
    relationName: 'solidityTestCases',
  }),
  reviewGradingTasks: many(lessons_review_grading_tasks, {
    relationName: 'reviewGradingTasks',
  }),
  reviewPaths: many(lessons_review_paths, {
    relationName: 'reviewPaths',
  }),
}))
export const relations_community_events = relations(community_events, ({ one }) => ({
  photo: one(media, {
    fields: [community_events.photo],
    references: [media.id],
    relationName: 'photo',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(payload_locked_documents_rels, ({ one }) => ({
  parent: one(payload_locked_documents, {
    fields: [payload_locked_documents_rels.parent],
    references: [payload_locked_documents.id],
    relationName: '_rels',
  }),
  usersID: one(users, {
    fields: [payload_locked_documents_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
  mediaID: one(media, {
    fields: [payload_locked_documents_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
  coursesID: one(courses, {
    fields: [payload_locked_documents_rels.coursesID],
    references: [courses.id],
    relationName: 'courses',
  }),
  modulesID: one(modules, {
    fields: [payload_locked_documents_rels.modulesID],
    references: [modules.id],
    relationName: 'modules',
  }),
  lessonsID: one(lessons, {
    fields: [payload_locked_documents_rels.lessonsID],
    references: [lessons.id],
    relationName: 'lessons',
  }),
  'community-eventsID': one(community_events, {
    fields: [payload_locked_documents_rels['community-eventsID']],
    references: [community_events.id],
    relationName: 'community-events',
  }),
}))
export const relations_payload_locked_documents = relations(payload_locked_documents, ({ many }) => ({
  _rels: many(payload_locked_documents_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_preferences_rels = relations(payload_preferences_rels, ({ one }) => ({
  parent: one(payload_preferences, {
    fields: [payload_preferences_rels.parent],
    references: [payload_preferences.id],
    relationName: '_rels',
  }),
  usersID: one(users, {
    fields: [payload_preferences_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
}))
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  db_schema: typeof db_schema
  enum_lessons_type: typeof enum_lessons_type
  enum_lessons_coding_language: typeof enum_lessons_coding_language
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  courses_tags: typeof courses_tags
  courses: typeof courses
  modules: typeof modules
  lessons_faq: typeof lessons_faq
  lessons_questions_options: typeof lessons_questions_options
  lessons_questions: typeof lessons_questions
  lessons_solidity_constructor_args: typeof lessons_solidity_constructor_args
  lessons_executable_test_cases: typeof lessons_executable_test_cases
  lessons_solidity_fixtures_constructor_args: typeof lessons_solidity_fixtures_constructor_args
  lessons_solidity_fixtures: typeof lessons_solidity_fixtures
  lessons_solidity_test_cases_steps_args: typeof lessons_solidity_test_cases_steps_args
  lessons_solidity_test_cases_steps: typeof lessons_solidity_test_cases_steps
  lessons_solidity_test_cases: typeof lessons_solidity_test_cases
  lessons_review_grading_tasks: typeof lessons_review_grading_tasks
  lessons_review_paths: typeof lessons_review_paths
  lessons: typeof lessons
  community_events: typeof community_events
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_courses_tags: typeof relations_courses_tags
  relations_courses: typeof relations_courses
  relations_modules: typeof relations_modules
  relations_lessons_faq: typeof relations_lessons_faq
  relations_lessons_questions_options: typeof relations_lessons_questions_options
  relations_lessons_questions: typeof relations_lessons_questions
  relations_lessons_solidity_constructor_args: typeof relations_lessons_solidity_constructor_args
  relations_lessons_executable_test_cases: typeof relations_lessons_executable_test_cases
  relations_lessons_solidity_fixtures_constructor_args: typeof relations_lessons_solidity_fixtures_constructor_args
  relations_lessons_solidity_fixtures: typeof relations_lessons_solidity_fixtures
  relations_lessons_solidity_test_cases_steps_args: typeof relations_lessons_solidity_test_cases_steps_args
  relations_lessons_solidity_test_cases_steps: typeof relations_lessons_solidity_test_cases_steps
  relations_lessons_solidity_test_cases: typeof relations_lessons_solidity_test_cases
  relations_lessons_review_grading_tasks: typeof relations_lessons_review_grading_tasks
  relations_lessons_review_paths: typeof relations_lessons_review_paths
  relations_lessons: typeof relations_lessons
  relations_community_events: typeof relations_community_events
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
