/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as CoursesCourseSlugRouteImport } from './routes/courses/$courseSlug'
import { Route as CommunitySlugRouteImport } from './routes/community/$slug'
import { Route as CertificatesCertificateIdRouteImport } from './routes/certificates/$certificateId'
import { Route as CoursesCourseSlugIndexRouteImport } from './routes/courses/$courseSlug.index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as AdminUsersUserIdIndexRouteImport } from './routes/admin/users/$userId.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as CoursesCourseSlugModuleSlugLessonSlugRouteImport } from './routes/courses/$courseSlug.$moduleSlug.$lessonSlug'
import { Route as AdminUsersUserIdCourseSlugLessonSlugRouteImport } from './routes/admin/users/$userId.$courseSlug.$lessonSlug'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugRoute = CoursesCourseSlugRouteImport.update({
  id: '/courses/$courseSlug',
  path: '/courses/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySlugRoute = CommunitySlugRouteImport.update({
  id: '/community/$slug',
  path: '/community/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesCertificateIdRoute =
  CertificatesCertificateIdRouteImport.update({
    id: '/certificates/$certificateId',
    path: '/certificates/$certificateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseSlugIndexRoute = CoursesCourseSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesCourseSlugRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdIndexRoute = AdminUsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersUserIdRoute,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugModuleSlugLessonSlugRoute =
  CoursesCourseSlugModuleSlugLessonSlugRouteImport.update({
    id: '/$moduleSlug/$lessonSlug',
    path: '/$moduleSlug/$lessonSlug',
    getParentRoute: () => CoursesCourseSlugRoute,
  } as any)
const AdminUsersUserIdCourseSlugLessonSlugRoute =
  AdminUsersUserIdCourseSlugLessonSlugRouteImport.update({
    id: '/$courseSlug/$lessonSlug',
    path: '/$courseSlug/$lessonSlug',
    getParentRoute: () => AdminUsersUserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/ranking': typeof RankingRoute
  '/sign-up': typeof SignUpRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/courses/$courseSlug/': typeof CoursesCourseSlugIndexRoute
  '/courses/$courseSlug/$moduleSlug/$lessonSlug': typeof CoursesCourseSlugModuleSlugLessonSlugRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/admin/users/$userId/$courseSlug/$lessonSlug': typeof AdminUsersUserIdCourseSlugLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/ranking': typeof RankingRoute
  '/sign-up': typeof SignUpRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugIndexRoute
  '/courses/$courseSlug/$moduleSlug/$lessonSlug': typeof CoursesCourseSlugModuleSlugLessonSlugRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/admin/users/$userId/$courseSlug/$lessonSlug': typeof AdminUsersUserIdCourseSlugLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/ranking': typeof RankingRoute
  '/sign-up': typeof SignUpRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteWithChildren
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/courses/$courseSlug/': typeof CoursesCourseSlugIndexRoute
  '/courses/$courseSlug/$moduleSlug/$lessonSlug': typeof CoursesCourseSlugModuleSlugLessonSlugRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/admin/users/$userId/$courseSlug/$lessonSlug': typeof AdminUsersUserIdCourseSlugLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/ranking'
    | '/sign-up'
    | '/certificates/$certificateId'
    | '/community/$slug'
    | '/courses/$courseSlug'
    | '/demo/tanstack-query'
    | '/profile/$username'
    | '/admin/'
    | '/courses/'
    | '/admin/users/$userId'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/courses/$courseSlug/'
    | '/courses/$courseSlug/$moduleSlug/$lessonSlug'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/admin/users/$userId/'
    | '/demo/start/ssr/'
    | '/admin/users/$userId/$courseSlug/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/ranking'
    | '/sign-up'
    | '/certificates/$certificateId'
    | '/community/$slug'
    | '/demo/tanstack-query'
    | '/profile/$username'
    | '/admin'
    | '/courses'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/courses/$courseSlug'
    | '/courses/$courseSlug/$moduleSlug/$lessonSlug'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/admin/users/$userId'
    | '/demo/start/ssr'
    | '/admin/users/$userId/$courseSlug/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/ranking'
    | '/sign-up'
    | '/certificates/$certificateId'
    | '/community/$slug'
    | '/courses/$courseSlug'
    | '/demo/tanstack-query'
    | '/profile/$username'
    | '/admin/'
    | '/courses/'
    | '/admin/users/$userId'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/courses/$courseSlug/'
    | '/courses/$courseSlug/$moduleSlug/$lessonSlug'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/admin/users/$userId/'
    | '/demo/start/ssr/'
    | '/admin/users/$userId/$courseSlug/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  RankingRoute: typeof RankingRoute
  SignUpRoute: typeof SignUpRoute
  CertificatesCertificateIdRoute: typeof CertificatesCertificateIdRoute
  CommunitySlugRoute: typeof CommunitySlugRoute
  CoursesCourseSlugRoute: typeof CoursesCourseSlugRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug': {
      id: '/courses/$courseSlug'
      path: '/courses/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof CoursesCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$slug': {
      id: '/community/$slug'
      path: '/community/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof CommunitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$certificateId': {
      id: '/certificates/$certificateId'
      path: '/certificates/$certificateId'
      fullPath: '/certificates/$certificateId'
      preLoaderRoute: typeof CertificatesCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug/': {
      id: '/courses/$courseSlug/'
      path: '/'
      fullPath: '/courses/$courseSlug/'
      preLoaderRoute: typeof CoursesCourseSlugIndexRouteImport
      parentRoute: typeof CoursesCourseSlugRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId/': {
      id: '/admin/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AdminUsersUserIdIndexRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug/$moduleSlug/$lessonSlug': {
      id: '/courses/$courseSlug/$moduleSlug/$lessonSlug'
      path: '/$moduleSlug/$lessonSlug'
      fullPath: '/courses/$courseSlug/$moduleSlug/$lessonSlug'
      preLoaderRoute: typeof CoursesCourseSlugModuleSlugLessonSlugRouteImport
      parentRoute: typeof CoursesCourseSlugRoute
    }
    '/admin/users/$userId/$courseSlug/$lessonSlug': {
      id: '/admin/users/$userId/$courseSlug/$lessonSlug'
      path: '/$courseSlug/$lessonSlug'
      fullPath: '/admin/users/$userId/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof AdminUsersUserIdCourseSlugLessonSlugRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
  }
}

interface AdminUsersUserIdRouteChildren {
  AdminUsersUserIdIndexRoute: typeof AdminUsersUserIdIndexRoute
  AdminUsersUserIdCourseSlugLessonSlugRoute: typeof AdminUsersUserIdCourseSlugLessonSlugRoute
}

const AdminUsersUserIdRouteChildren: AdminUsersUserIdRouteChildren = {
  AdminUsersUserIdIndexRoute: AdminUsersUserIdIndexRoute,
  AdminUsersUserIdCourseSlugLessonSlugRoute:
    AdminUsersUserIdCourseSlugLessonSlugRoute,
}

const AdminUsersUserIdRouteWithChildren =
  AdminUsersUserIdRoute._addFileChildren(AdminUsersUserIdRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesCourseSlugRouteChildren {
  CoursesCourseSlugIndexRoute: typeof CoursesCourseSlugIndexRoute
  CoursesCourseSlugModuleSlugLessonSlugRoute: typeof CoursesCourseSlugModuleSlugLessonSlugRoute
}

const CoursesCourseSlugRouteChildren: CoursesCourseSlugRouteChildren = {
  CoursesCourseSlugIndexRoute: CoursesCourseSlugIndexRoute,
  CoursesCourseSlugModuleSlugLessonSlugRoute:
    CoursesCourseSlugModuleSlugLessonSlugRoute,
}

const CoursesCourseSlugRouteWithChildren =
  CoursesCourseSlugRoute._addFileChildren(CoursesCourseSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  RankingRoute: RankingRoute,
  SignUpRoute: SignUpRoute,
  CertificatesCertificateIdRoute: CertificatesCertificateIdRoute,
  CommunitySlugRoute: CommunitySlugRoute,
  CoursesCourseSlugRoute: CoursesCourseSlugRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
