/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as CoursesCourseSlugRouteImport } from './routes/courses/$courseSlug'
import { Route as CommunitySlugRouteImport } from './routes/community/$slug'
import { Route as CertificatesCertificateIdRouteImport } from './routes/certificates/$certificateId'
import { Route as CoursesCourseSlugIndexRouteImport } from './routes/courses/$courseSlug.index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as CoursesCourseSlugCertificateRouteImport } from './routes/courses/$courseSlug.certificate'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as CoursesCourseSlugModuleSlugLessonSlugRouteImport } from './routes/courses/$courseSlug.$moduleSlug.$lessonSlug'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugRoute = CoursesCourseSlugRouteImport.update({
  id: '/courses/$courseSlug',
  path: '/courses/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySlugRoute = CommunitySlugRouteImport.update({
  id: '/community/$slug',
  path: '/community/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesCertificateIdRoute =
  CertificatesCertificateIdRouteImport.update({
    id: '/certificates/$certificateId',
    path: '/certificates/$certificateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseSlugIndexRoute = CoursesCourseSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesCourseSlugRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugCertificateRoute =
  CoursesCourseSlugCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => CoursesCourseSlugRoute,
  } as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugModuleSlugLessonSlugRoute =
  CoursesCourseSlugModuleSlugLessonSlugRouteImport.update({
    id: '/$moduleSlug/$lessonSlug',
    path: '/$moduleSlug/$lessonSlug',
    getParentRoute: () => CoursesCourseSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-up': typeof SignUpRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/courses/': typeof CoursesIndexRoute
  '/courses/$courseSlug/certificate': typeof CoursesCourseSlugCertificateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/courses/$courseSlug/': typeof CoursesCourseSlugIndexRoute
  '/courses/$courseSlug/$moduleSlug/$lessonSlug': typeof CoursesCourseSlugModuleSlugLessonSlugRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-up': typeof SignUpRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/courses': typeof CoursesIndexRoute
  '/courses/$courseSlug/certificate': typeof CoursesCourseSlugCertificateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugIndexRoute
  '/courses/$courseSlug/$moduleSlug/$lessonSlug': typeof CoursesCourseSlugModuleSlugLessonSlugRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-up': typeof SignUpRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/courses/': typeof CoursesIndexRoute
  '/courses/$courseSlug/certificate': typeof CoursesCourseSlugCertificateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/courses/$courseSlug/': typeof CoursesCourseSlugIndexRoute
  '/courses/$courseSlug/$moduleSlug/$lessonSlug': typeof CoursesCourseSlugModuleSlugLessonSlugRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-up'
    | '/certificates/$certificateId'
    | '/community/$slug'
    | '/courses/$courseSlug'
    | '/demo/tanstack-query'
    | '/courses/'
    | '/courses/$courseSlug/certificate'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/courses/$courseSlug/'
    | '/courses/$courseSlug/$moduleSlug/$lessonSlug'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-up'
    | '/certificates/$certificateId'
    | '/community/$slug'
    | '/demo/tanstack-query'
    | '/courses'
    | '/courses/$courseSlug/certificate'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/courses/$courseSlug'
    | '/courses/$courseSlug/$moduleSlug/$lessonSlug'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/sign-up'
    | '/certificates/$certificateId'
    | '/community/$slug'
    | '/courses/$courseSlug'
    | '/demo/tanstack-query'
    | '/courses/'
    | '/courses/$courseSlug/certificate'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/courses/$courseSlug/'
    | '/courses/$courseSlug/$moduleSlug/$lessonSlug'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignUpRoute: typeof SignUpRoute
  CertificatesCertificateIdRoute: typeof CertificatesCertificateIdRoute
  CommunitySlugRoute: typeof CommunitySlugRoute
  CoursesCourseSlugRoute: typeof CoursesCourseSlugRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug': {
      id: '/courses/$courseSlug'
      path: '/courses/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof CoursesCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$slug': {
      id: '/community/$slug'
      path: '/community/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof CommunitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$certificateId': {
      id: '/certificates/$certificateId'
      path: '/certificates/$certificateId'
      fullPath: '/certificates/$certificateId'
      preLoaderRoute: typeof CertificatesCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug/': {
      id: '/courses/$courseSlug/'
      path: '/'
      fullPath: '/courses/$courseSlug/'
      preLoaderRoute: typeof CoursesCourseSlugIndexRouteImport
      parentRoute: typeof CoursesCourseSlugRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug/certificate': {
      id: '/courses/$courseSlug/certificate'
      path: '/certificate'
      fullPath: '/courses/$courseSlug/certificate'
      preLoaderRoute: typeof CoursesCourseSlugCertificateRouteImport
      parentRoute: typeof CoursesCourseSlugRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug/$moduleSlug/$lessonSlug': {
      id: '/courses/$courseSlug/$moduleSlug/$lessonSlug'
      path: '/$moduleSlug/$lessonSlug'
      fullPath: '/courses/$courseSlug/$moduleSlug/$lessonSlug'
      preLoaderRoute: typeof CoursesCourseSlugModuleSlugLessonSlugRouteImport
      parentRoute: typeof CoursesCourseSlugRoute
    }
  }
}

interface CoursesCourseSlugRouteChildren {
  CoursesCourseSlugCertificateRoute: typeof CoursesCourseSlugCertificateRoute
  CoursesCourseSlugIndexRoute: typeof CoursesCourseSlugIndexRoute
  CoursesCourseSlugModuleSlugLessonSlugRoute: typeof CoursesCourseSlugModuleSlugLessonSlugRoute
}

const CoursesCourseSlugRouteChildren: CoursesCourseSlugRouteChildren = {
  CoursesCourseSlugCertificateRoute: CoursesCourseSlugCertificateRoute,
  CoursesCourseSlugIndexRoute: CoursesCourseSlugIndexRoute,
  CoursesCourseSlugModuleSlugLessonSlugRoute:
    CoursesCourseSlugModuleSlugLessonSlugRoute,
}

const CoursesCourseSlugRouteWithChildren =
  CoursesCourseSlugRoute._addFileChildren(CoursesCourseSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignUpRoute: SignUpRoute,
  CertificatesCertificateIdRoute: CertificatesCertificateIdRoute,
  CommunitySlugRoute: CommunitySlugRoute,
  CoursesCourseSlugRoute: CoursesCourseSlugRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
