/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as CoursesCourseSlugRouteImport } from './routes/courses/$courseSlug'
import { Route as CommunitySlugRouteImport } from './routes/community/$slug'
import { Route as CertificatesCertificateIdRouteImport } from './routes/certificates/$certificateId'
import { Route as CoursesCourseSlugIndexRouteImport } from './routes/courses/$courseSlug.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminUsersUserIdIndexRouteImport } from './routes/admin/users/$userId.index'
import { Route as CoursesCourseSlugModuleSlugLessonSlugRouteImport } from './routes/courses/$courseSlug.$moduleSlug.$lessonSlug'
import { Route as AdminUsersUserIdCourseSlugLessonSlugRouteImport } from './routes/admin/users/$userId.$courseSlug.$lessonSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugRoute = CoursesCourseSlugRouteImport.update({
  id: '/courses/$courseSlug',
  path: '/courses/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySlugRoute = CommunitySlugRouteImport.update({
  id: '/community/$slug',
  path: '/community/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesCertificateIdRoute =
  CertificatesCertificateIdRouteImport.update({
    id: '/certificates/$certificateId',
    path: '/certificates/$certificateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseSlugIndexRoute = CoursesCourseSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesCourseSlugRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdIndexRoute = AdminUsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersUserIdRoute,
} as any)
const CoursesCourseSlugModuleSlugLessonSlugRoute =
  CoursesCourseSlugModuleSlugLessonSlugRouteImport.update({
    id: '/$moduleSlug/$lessonSlug',
    path: '/$moduleSlug/$lessonSlug',
    getParentRoute: () => CoursesCourseSlugRoute,
  } as any)
const AdminUsersUserIdCourseSlugLessonSlugRoute =
  AdminUsersUserIdCourseSlugLessonSlugRouteImport.update({
    id: '/$courseSlug/$lessonSlug',
    path: '/$courseSlug/$lessonSlug',
    getParentRoute: () => AdminUsersUserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/ranking': typeof RankingRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteWithChildren
  '/courses/$courseSlug/': typeof CoursesCourseSlugIndexRoute
  '/courses/$courseSlug/$moduleSlug/$lessonSlug': typeof CoursesCourseSlugModuleSlugLessonSlugRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/admin/users/$userId/$courseSlug/$lessonSlug': typeof AdminUsersUserIdCourseSlugLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/ranking': typeof RankingRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugIndexRoute
  '/courses/$courseSlug/$moduleSlug/$lessonSlug': typeof CoursesCourseSlugModuleSlugLessonSlugRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
  '/admin/users/$userId/$courseSlug/$lessonSlug': typeof AdminUsersUserIdCourseSlugLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/ranking': typeof RankingRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/certificates/$certificateId': typeof CertificatesCertificateIdRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRouteWithChildren
  '/courses/$courseSlug/': typeof CoursesCourseSlugIndexRoute
  '/courses/$courseSlug/$moduleSlug/$lessonSlug': typeof CoursesCourseSlugModuleSlugLessonSlugRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/admin/users/$userId/$courseSlug/$lessonSlug': typeof AdminUsersUserIdCourseSlugLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/ranking'
    | '/sign-up'
    | '/sitemap.xml'
    | '/certificates/$certificateId'
    | '/community/$slug'
    | '/courses/$courseSlug'
    | '/profile/$username'
    | '/admin/'
    | '/courses/'
    | '/admin/users/$userId'
    | '/courses/$courseSlug/'
    | '/courses/$courseSlug/$moduleSlug/$lessonSlug'
    | '/admin/users/$userId/'
    | '/admin/users/$userId/$courseSlug/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/ranking'
    | '/sign-up'
    | '/sitemap.xml'
    | '/certificates/$certificateId'
    | '/community/$slug'
    | '/profile/$username'
    | '/admin'
    | '/courses'
    | '/courses/$courseSlug'
    | '/courses/$courseSlug/$moduleSlug/$lessonSlug'
    | '/admin/users/$userId'
    | '/admin/users/$userId/$courseSlug/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/ranking'
    | '/sign-up'
    | '/sitemap.xml'
    | '/certificates/$certificateId'
    | '/community/$slug'
    | '/courses/$courseSlug'
    | '/profile/$username'
    | '/admin/'
    | '/courses/'
    | '/admin/users/$userId'
    | '/courses/$courseSlug/'
    | '/courses/$courseSlug/$moduleSlug/$lessonSlug'
    | '/admin/users/$userId/'
    | '/admin/users/$userId/$courseSlug/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  RankingRoute: typeof RankingRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CertificatesCertificateIdRoute: typeof CertificatesCertificateIdRoute
  CommunitySlugRoute: typeof CommunitySlugRoute
  CoursesCourseSlugRoute: typeof CoursesCourseSlugRouteWithChildren
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug': {
      id: '/courses/$courseSlug'
      path: '/courses/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof CoursesCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$slug': {
      id: '/community/$slug'
      path: '/community/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof CommunitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$certificateId': {
      id: '/certificates/$certificateId'
      path: '/certificates/$certificateId'
      fullPath: '/certificates/$certificateId'
      preLoaderRoute: typeof CertificatesCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug/': {
      id: '/courses/$courseSlug/'
      path: '/'
      fullPath: '/courses/$courseSlug/'
      preLoaderRoute: typeof CoursesCourseSlugIndexRouteImport
      parentRoute: typeof CoursesCourseSlugRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId/': {
      id: '/admin/users/$userId/'
      path: '/'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AdminUsersUserIdIndexRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
    '/courses/$courseSlug/$moduleSlug/$lessonSlug': {
      id: '/courses/$courseSlug/$moduleSlug/$lessonSlug'
      path: '/$moduleSlug/$lessonSlug'
      fullPath: '/courses/$courseSlug/$moduleSlug/$lessonSlug'
      preLoaderRoute: typeof CoursesCourseSlugModuleSlugLessonSlugRouteImport
      parentRoute: typeof CoursesCourseSlugRoute
    }
    '/admin/users/$userId/$courseSlug/$lessonSlug': {
      id: '/admin/users/$userId/$courseSlug/$lessonSlug'
      path: '/$courseSlug/$lessonSlug'
      fullPath: '/admin/users/$userId/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof AdminUsersUserIdCourseSlugLessonSlugRouteImport
      parentRoute: typeof AdminUsersUserIdRoute
    }
  }
}

interface AdminUsersUserIdRouteChildren {
  AdminUsersUserIdIndexRoute: typeof AdminUsersUserIdIndexRoute
  AdminUsersUserIdCourseSlugLessonSlugRoute: typeof AdminUsersUserIdCourseSlugLessonSlugRoute
}

const AdminUsersUserIdRouteChildren: AdminUsersUserIdRouteChildren = {
  AdminUsersUserIdIndexRoute: AdminUsersUserIdIndexRoute,
  AdminUsersUserIdCourseSlugLessonSlugRoute:
    AdminUsersUserIdCourseSlugLessonSlugRoute,
}

const AdminUsersUserIdRouteWithChildren =
  AdminUsersUserIdRoute._addFileChildren(AdminUsersUserIdRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesCourseSlugRouteChildren {
  CoursesCourseSlugIndexRoute: typeof CoursesCourseSlugIndexRoute
  CoursesCourseSlugModuleSlugLessonSlugRoute: typeof CoursesCourseSlugModuleSlugLessonSlugRoute
}

const CoursesCourseSlugRouteChildren: CoursesCourseSlugRouteChildren = {
  CoursesCourseSlugIndexRoute: CoursesCourseSlugIndexRoute,
  CoursesCourseSlugModuleSlugLessonSlugRoute:
    CoursesCourseSlugModuleSlugLessonSlugRoute,
}

const CoursesCourseSlugRouteWithChildren =
  CoursesCourseSlugRoute._addFileChildren(CoursesCourseSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  RankingRoute: RankingRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CertificatesCertificateIdRoute: CertificatesCertificateIdRoute,
  CommunitySlugRoute: CommunitySlugRoute,
  CoursesCourseSlugRoute: CoursesCourseSlugRouteWithChildren,
  ProfileUsernameRoute: ProfileUsernameRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
