name: Deploy Lecture Admin to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - 'apps/lecture-admin/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy Lecture Admin to Cloudflare Workers
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build and Deploy
        working-directory: apps/lecture-admin
        run: yarn deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          KEYSTATIC_GITHUB_CLIENT_ID: ${{ secrets.KEYSTATIC_GITHUB_CLIENT_ID }}
          KEYSTATIC_GITHUB_CLIENT_SECRET: ${{ secrets.KEYSTATIC_GITHUB_CLIENT_SECRET }}
          KEYSTATIC_SECRET: ${{ secrets.KEYSTATIC_SECRET }}
          NEXT_PUBLIC_KEYSTATIC_GITHUB_APP_SLUG: ${{ secrets.NEXT_PUBLIC_KEYSTATIC_GITHUB_APP_SLUG }}
